### ISSUE TITLE
Whats the verdict

### ISSUE THREAD

**Issue by scorp12** [VictorSavu/SPITFIRE#4]
Whats the status of this project

**Comment by scorp12** [comment]
U have any time for project

**Comment by VictorSavu** [comment]
Evony is a dead game, there is no reason for trying to replicate this game, even if we did, we might have problems with their flash client regarding copyright

**Comment by Xnc** [comment]
The client can be changed.

**Comment by insan1tyevo** [comment]
Are either of you still interested / working on this project? I have made contact with the original developer of Spitfire Daisy and im currently seeking people who have experience with Spitfire that would still be interested in developing an EPS for the community...
Contact my Skype: live:x2GZqo4C

**Comment by Xnc** [comment]
Yes we working, i have doubt you contacted Daisy, what skype ID it is this ?

**Comment by insan1tyevo** [comment]
Its fine, we have a few developers interested in working on this project already with one more confirming within the next 48 hours. Thanks for your time.

**Comment by Xnc** [comment]
https://github.com/Xnc/spitfireiii/blob/master/bin/readme.md
